swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger"
host: "6sy9tbgmi3.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
tags:
- name: "products"
schemes:
- "https"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "Get list of products"
      description: "Returns all products"
      operationId: "getAllProducts"
      responses: 
        "200": 
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        "500":
          description: "Internal server error"
  /products/{productID}:
    get:
      tags:
      - "products"
      summary: "Get product by ID"
      description: "Returns a single product"
      operationId: "getProductByID"
      parameters:
      - name: "productID"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "500":
          description: "Internal server error"
definitions:
  Product:
    type: object
    properties:
      count:
        type: "integer"
        format: "int64"
      description:
        type: "string"
      id:
        type: "integer"
        format: "int64"
      price:
        type: "integer"
        format: "int64"
      title:
        type: "string"